name: red-wine-train
type: job
image:
  type: build
  build_source:
    type: local
  build_spec:
    type: tfy-python-buildpack
    command: python train.py
env:
  TFY_API_KEY: tfy-secret://user-truefoundry:red-wine-sg:TFY_API_KEY
