name: red-wine-train
components:
- name: red-wine-train
  type: job
  image:
    type: build
    build_source:
      type: local
    build_spec:
      type: tfy-python-buildpack
      command: python train.py
  env:
    TFY_HOST: tfy-secret://user-truefoundry:red-wine-sg:TFY_HOST
    TFY_API_KEY: tfy-secret://user-truefoundry:red-wine-sg:TFY_API_KEY
