# Replace <workspace_name> with your created workspace name.

name: Servicefoundry CI/CD Automation Example

on:
  push:
    branches:
      - main

jobs:
  production_deploy:
    runs-on: ubuntu-latest
    env:
      TFY_API_KEY: ${{ secrets.TFY_API_KEY }}
      WORKSPACE_FQN: <workspace_name>
    steps:
      - uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install servicefoundry-cli library
        run: pip install "servicefoundry>=0.2.14,<0.3.0"

      - name: Deploy on servicefoundry server
        run: sfy deploy --file servicefoundry.yaml --workspace-fqn "${WORKSPACE_FQN}"
