name: iris-train-cron-job
type: job
image:
  type: build
  build_source:
    type: local
  build_spec:
    type: tfy-python-buildpack
    command: python retrain.py
env:
  TFY_API_KEY: "<Paste your API KEY>"
  MLF_MODEL_VERSION_FQN: "<Paste model version fqn here>"
trigger:
  type: scheduled
  schedule: "0 0 * * 0"
  concurrency_policy: "Forbid"
