name: Servicefoundry CI/CD Automation Example

on:
  push:
    branches:
      - main
    paths:
      - 'deployment/ci-cd-automation/*'

jobs:
  production_deploy:
    runs-on: ubuntu-latest
    env:
      TFY_HOST: https://app.develop.truefoundry.tech
      TFY_API_KEY: ${{ secrets.TFY_API_KEY }}
      WORKSPACE_FQN: tfy-dev-cluster:ci-cd-examples
    steps:
      - uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install servicefoundry-cli library
        run: pip install "servicefoundry>=0.2.14,<0.3.0"

      - name: Deploy on servicefoundry server
        working-directory: ./ci-cd-automation
        run: sfy deploy --file servicefoundry.yaml --workspace-fqn "${WORKSPACE_FQN}"
