name: churn-prediction-train
type: job
image:
  type: build
  build_spec:
    type: tfy-python-buildpack
    command: >-
      python main.py --n_neighbors {{n_neighbors}} --weights {{weights}}
      --algorithm {{algorithm}} --power {{power}} --leaf_size {{leaf_size}}
      --metric {{metric}} --n_jobs {{n_jobs}}
    python_version: '3.9'
    requirements_path: requirements.txt
    build_context_path: ./
  build_source:
    type: local
params:
  - name: n_neighbors
    default: '5'
    param_type: string
    description: Number of neighbors to use by default
  - name: weights
    default: uniform
    param_type: string
    description: 'Weight function used in prediction.  Possible values: uniform, distance'
  - name: algorithm
    default: auto
    param_type: string
    description: >-
      Algorithm used to compute the nearest neighbors: possible values: 'auto',
      'ball_tree', 'kd_tree', 'brute'
  - name: power
    default: '2'
    param_type: string
    description: >-
      Power parameter for the Minkowski metric. When p = 1, this is
      manhattan_dist, and euclidean_dist p = 2
  - name: leaf_size
    default: '30'
    param_type: string
    description: Leaf size passed to BallTree or KDTree
  - name: metric
    default: minkowski
    param_type: string
    description: The distance metric to use for the tree. The default metric is minkowski,
  - name: n_jobs
    default: '1'
    param_type: string
    description: The number of parallel jobs to run for neighbors search
retries: 0
trigger:
  type: manual
resources:
  cpu_limit: 1
  gpu_count: 0
  cpu_request: 1
  memory_limit: 2000
  memory_request: 2000
  ephemeral_storage_limit: 2000
  ephemeral_storage_request: 1000
