name: counter-job
type: job
image:
  type: build
  build_spec:
    type: tfy-python-buildpack
    command: python run.py
    python_version: '3.9'
    build_context_path: ./
  build_source:
    type: local
restart: Never
retries: 1
timeout: 1000
trigger:
  type: manual
resources:
  cpu_limit: 1
  cpu_request: 0.5
  memory_limit: 500
  memory_request: 200
  ephemeral_storage_limit: 2000
  ephemeral_storage_request: 1000
failed_jobs_history_limit: 20
successful_jobs_history_limit: 20
